### ISSUE TITLE
RuntimeError: DNF error: Problems in request:

### ISSUE THREAD

**Issue by cmoulliard** [konflux-ci/rpm-lockfile-prototype#67]
## Issue

When we try to grab the urls of RPMs for fedora, we got such an error

```
Failed to set locale, defaulting to C.UTF-8
INFO:root:Running solver for x86_64
INFO:root:$ skopeo --override-arch=amd64 copy docker://fedora dir:/tmp/tmp8kt_7dmw
Getting image source signatures
Copying blob f7bb57d05c2a done   |
Copying config eca85b75dc done   |
Writing manifest to image destination
INFO:root:Extracting rpmdb from layer sha256:f7bb57d05c2a01f21aeee5873ebc9afe04304b3f5ea7b4c47e0ce18ac2d38124
INFO:dnf:Added updates repo from
INFO:dnf:Added updates-debuginfo repo from
INFO:dnf:Added updates-source repo from
INFO:dnf:Added fedora repo from
INFO:dnf:Added fedora-debuginfo repo from
INFO:dnf:Added fedora-source repo from
INFO:dnf:Last metadata expiration check: 0:00:01 ago on Fri Oct 18 12:31:09 2024.
ERROR:dnf:No match for argument: golang
ERROR:dnf:No match for argument: podman
ERROR:dnf:No match for argument: jq
ERROR:root:Problems in request:
missing packages: golang, podman, jq
Traceback (most recent call last):
  File "/home/cloud-user/.local/lib/python3.9/site-packages/rpm_lockfile/__init__.py", line 155, in resolver
    base.install_specs(solvables)
  File "/usr/lib/python3.9/site-packages/dnf/base.py", line 2053, in install_specs
    raise dnf.exceptions.MarkingErrors(no_match_group_specs=no_match_group_specs,
dnf.exceptions.MarkingErrors: Problems in request:
missing packages: golang, podman, jq

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cloud-user/.local/bin/rpm-lockfile-prototype", line 8, in <module>
    sys.exit(main())
  File "/home/cloud-user/.local/lib/python3.9/site-packages/rpm_lockfile/__init__.py", line 439, in main
    process_arch(
  File "/home/cloud-user/.local/lib/python3.9/site-packages/rpm_lockfile/__init__.py", line 244, in process_arch
    packages, sources, module_metadata = resolver(
  File "/home/cloud-user/.local/lib/python3.9/site-packages/rpm_lockfile/__init__.py", line 158, in resolver
    raise RuntimeError(f"DNF error: {exc}")
RuntimeError: DNF error: Problems in request:
missing packages: golang, podman, jq
```

Command executed
```
git clone https://github.com/redhat-buildpacks/paketo-container
cd paketo-container
podman run --rm -v "$PWD:$PWD:z" -w "$PWD" fedora cp -r /etc/yum.repos.d/. .
rpm-lockfile-prototype -f Containerfile rpms.in.yaml --outfile rpms.lock.yaml
```

Repo File
```
rpms.in.yaml
contentOrigin:
  repofiles:
    - ./fedora-updates.repo
    - ./fedora.repo
packages:
  - golang
  - podman
  - jq
  - gettext
```

fedora.repo
```
cat fedora.repo
[fedora]
name=Fedora $releasever - $basearch
#baseurl=http://download.example/pub/fedora/linux/releases/$releasever/Everything/$basearch/os/
metalink=https://mirrors.fedoraproject.org/metalink?repo=fedora-$releasever&arch=$basearch
enabled=1
countme=1
metadata_expire=7d
repo_gpgcheck=0
type=rpm
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$releasever-$basearch
skip_if_unavailable=False

[fedora-debuginfo]
name=Fedora $releasever - $basearch - Debug
#baseurl=http://download.example/pub/fedora/linux/releases/$releasever/Everything/$basearch/debug/tree/
metalink=https://mirrors.fedoraproject.org/metalink?repo=fedora-debug-$releasever&arch=$basearch
enabled=0
metadata_expire=7d
repo_gpgcheck=0
type=rpm
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$releasever-$basearch
skip_if_unavailable=False

[fedora-source]
name=Fedora $releasever - Source
#baseurl=http://download.example/pub/fedora/linux/releases/$releasever/Everything/source/tree/
metalink=https://mirrors.fedoraproject.org/metalink?repo=fedora-source-$releasever&arch=$basearch
enabled=0
metadata_expire=7d
repo_gpgcheck=0
type=rpm
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$releasever-$basearch
skip_if_unavailable=False
```

**Comment by lubomir** [comment]
The error is that dnf doesn't find the requested packages in the provided repo. That's strange, as Fedora does package all of them.

I tried replicating this locally, but it does work for me.

This is quite possibly caused by the metalink. Maybe it's getting resolved to a mirror that is out dated. Does it happen consistently over time?

In general, metalinks are only good for experimenting and playing around with the tool. It seems to me that's what you are doing here, given the `fedora` image with no tag. You could try pointing directly at a Fedora compose by setting `baseurl` to one of the following:
`https://kojipkgs.fedoraproject.org/compose/branched/latest-Fedora-41/compose/Everything/$basearch/os`
`https://kojipkgs.fedoraproject.org/compose/rawhide/latest-Fedora-Rawhide/compose/Everything/$basearch/os`
There's no compose for the released versions though.

**Comment by cmoulliard** [comment]
> This is quite possibly caused by the metalink. Maybe it's getting resolved to a mirror that is out dated. Does it happen consistently over time?

Yes. I did a test right now and got the same error

**Comment by cmoulliard** [comment]
> In general, metalinks are only good for experimenting and playing around with the tool. It seems to me that's what you are doing here, given the `fedora` image with no tag. You could try pointing directly at a Fedora compose by setting `baseurl` to one of the following:

Are you saying that such an issue could be resolved if I specify the fedora version to be used from this command `podman run --rm -v "$PWD:$PWD:z" -w "$PWD" fedora cp -r /etc/yum.repos.d/. .` ?

**Comment by cmoulliard** [comment]
Here is a new test which is failing too using fedora:40

```
[cloud-user@rhel-9 paketo-container]$ podman run --rm -v "$PWD:$PWD:z" -w "$PWD" fedora:40 cp -r /etc/yum.repos.d/. .
Resolved "fedora" as an alias (/etc/containers/registries.conf.d/000-shortnames.conf)
Trying to pull registry.fedoraproject.org/fedora:40...
Getting image source signatures
Copying blob 311336741819 done   |
Copying config 8bf3872d7a done   |
Writing manifest to image destination

$ rpm-lockfile-prototype -f Containerfile rpms.in.yaml --outfile rpms.lock.yaml
Failed to set locale, defaulting to C.UTF-8
INFO:root:Running solver for x86_64
INFO:root:$ skopeo --override-arch=amd64 copy docker://fedora dir:/tmp/tmpjipyr8kd
Getting image source signatures
Copying blob f7bb57d05c2a done   |
Copying config eca85b75dc done   |
Writing manifest to image destination
INFO:root:Extracting rpmdb from layer sha256:f7bb57d05c2a01f21aeee5873ebc9afe04304b3f5ea7b4c47e0ce18ac2d38124
INFO:dnf:Added updates repo from
INFO:dnf:Added updates-debuginfo repo from
INFO:dnf:Added updates-source repo from
INFO:dnf:Added fedora repo from
INFO:dnf:Added fedora-debuginfo repo from
INFO:dnf:Added fedora-source repo from
ERROR:dnf:No match for argument: podman
ERROR:dnf:No match for argument: golang
ERROR:dnf:No match for argument: jq
ERROR:root:Problems in request:
missing packages: podman, golang, jq
Traceback (most recent call last):
  File "/home/cloud-user/.local/lib/python3.9/site-packages/rpm_lockfile/__init__.py", line 155, in resolver
    base.install_specs(solvables)
  File "/usr/lib/python3.9/site-packages/dnf/base.py", line 2053, in install_specs
    raise dnf.exceptions.MarkingErrors(no_match_group_specs=no_match_group_specs,
dnf.exceptions.MarkingErrors: Problems in request:
missing packages: podman, golang, jq

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cloud-user/.local/bin/rpm-lockfile-prototype", line 8, in <module>
    sys.exit(main())
  File "/home/cloud-user/.local/lib/python3.9/site-packages/rpm_lockfile/__init__.py", line 439, in main
    process_arch(
  File "/home/cloud-user/.local/lib/python3.9/site-packages/rpm_lockfile/__init__.py", line 244, in process_arch
    packages, sources, module_metadata = resolver(
  File "/home/cloud-user/.local/lib/python3.9/site-packages/rpm_lockfile/__init__.py", line 158, in resolver
    raise RuntimeError(f"DNF error: {exc}")
RuntimeError: DNF error: Problems in request:
missing packages: podman, golang, jq
```

**Comment by lubomir** [comment]
> Are you saying that such an issue could be resolved if I specify the fedora version to be used from this command `podman run --rm -v "$PWD:$PWD:z" -w "$PWD" fedora cp -r /etc/yum.repos.d/. .` ?

Nope, I meant replacing the metalink option in the repo file with a baseurl. The URLs I provided would work for 41 and Rawhide, but I don't have one for 40. Alternatively you could put this into the input yaml file (instead of the current section):

```yaml
contentOrigin:
  repos:
    - repoid: fedora
      baseurl: https://kojipkgs.fedoraproject.org/compose/branched/latest-Fedora-41/compose/Everything/$basearch/os
```

**Comment by cmoulliard** [comment]
Hmmmm. I got another problem during image build as cachi2 reports such an error
```
Adding /tmp/cachi2/output/deps/rpm/x86_64/repos.d/cachi2.repo to fetched.repos.d
Adding the entitlement to the build
[1/2] STEP 1/14: FROM fedora AS builder
[1/2] STEP 2/14: RUN . /cachi2/cachi2.env &&     dnf -y install golang
Repository 'fedora' is missing name in configuration, using id.
fedora                                           13 MB/s |  62 kB     00:00    
Error: 
 Problem: package golang-1.22.1-1.fc40.x86_64 from fedora requires golang-bin = 1.22.1-1.fc40, but none of the providers can be installed
  - package golang-bin-1.22.1-1.fc40.x86_64 from fedora requires gcc, but none of the providers can be installed
  - conflicting requests
  - nothing provides libgomp = 14.0.1-0.15.fc40 needed by gcc-14.0.1-0.15.fc40.x86_64 from fedora
(try to add '--skip-broken' to skip uninstallable packages)
subprocess exited with status 1
subprocess exited with status 1
```

**Comment by cmoulliard** [comment]
That fails when Tekton prefetch pod download the bits using fedora:40 too 
```
[build] Trying to pull registry.fedoraproject.org/fedora:40...
[build] Getting image source signatures
[build] Copying blob sha256:311336741819859e92064b81199a47397788d736d764f561a89cba9583600387
[build] Copying config sha256:8bf3872d7acb45c472225350d631e1bf091ea3b1e1f466521e78102f7deea864
[build] Writing manifest to image destination
[build] 8bf3872d7acb45c472225350d631e1bf091ea3b1e1f466521e78102f7deea864
[build] 8bf3872d7acb45c472225350d631e1bf091ea3b1e1f466521e78102f7deea864
[build] Build will be executed with network isolation
[build] Prefetched content will be made available
[build] Adding /tmp/cachi2/output/deps/rpm/x86_64/repos.d/cachi2.repo to fetched.repos.d
[build] Adding the entitlement to the build
[build] [1/2] STEP 1/14: FROM fedora:40 AS builder
[build] [1/2] STEP 2/14: RUN . /cachi2/cachi2.env &&     dnf -y install golang
[build] Repository 'fedora' is missing name in configuration, using id.
[build] fedora                                           12 MB/s |  62 kB     00:00  
[build] Error: 
[build]  Problem: package golang-1.22.1-1.fc40.x86_64 from fedora requires golang-bin = 1.22.1-1.fc40, but none of the providers can be installed
[build]   - package golang-bin-1.22.1-1.fc40.x86_64 from fedora requires gcc, but none of the providers can be installed
[build]   - conflicting requests
[build]   - nothing provides libgomp = 14.0.1-0.15.fc40 needed by gcc-14.0.1-0.15.fc40.x86_64 from fedora
[build] (try to add '--skip-broken' to skip uninstallable packages)
[build] subprocess exited with status 1
[build] subprocess exited with status 1
[build] Error: building at STEP "RUN . /cachi2/cachi2.env &&     dnf -y install golang": exit status 1  
```

**Comment by cmoulliard** [comment]
Using `[2/2] STEP 1/13: FROM registry.fedoraproject.org/fedora:40` fixed the issue

![Screenshot 2024-10-21 at 19 01 12](https://github.com/user-attachments/assets/100a10b7-760e-437b-972c-cbf543358052)

**Comment by lubomir** [comment]
Great to hear that.

To summarize, we have found two potential issues here:
* Mirrorlist and metalink isn't very reliable here. It works great for bare dnf, so maybe the tool is doing something wrong.
* Using image name without registry can lead to confusing errors. #68 should help there by printing a big warning.
