### ISSUE TITLE
PackagesNotAvailableError when reinstalling from (RH) internal Pulp

### ISSUE THREAD

**Issue by jpopelka** [konflux-ci/rpm-lockfile-prototype#69]
Hi Lubomir

[Toolbox image reinstalls lots of packages](https://gitlab.com/redhat/rhel/containers/toolbox/-/blob/rhel-9.5.0/rpms.in.yaml?ref_type=heads#L56).

Resolving the RPM lockfile has been working OK with nightly composes

```yaml
contentOrigin:
  repos:
    - repoid: rhel-9-base
      baseurl: "https://download.devel.redhat.com/rhel-9/nightly/updates/RHEL-9/RHEL-9.5.0-updates-20241029.3/compose/BaseOS/$basearch/os/"
    - repoid: rhel-9-base-source
      baseurl: "https://download.devel.redhat.com/rhel-9/nightly/updates/RHEL-9/RHEL-9.5.0-updates-20241029.3/compose/BaseOS/source/tree/"
    - repoid: rhel-9-appstream
      baseurl: "https://download.devel.redhat.com/rhel-9/nightly/updates/RHEL-9/RHEL-9.5.0-updates-20241029.3/compose/AppStream/$basearch/os/"
    - repoid: rhel-9-appstream-source
      baseurl: "https://download.devel.redhat.com/rhel-9/nightly/updates/RHEL-9/RHEL-9.5.0-updates-20241029.3/compose/AppStream/source/tree/"
```

but I now want to change that to internal Pulp repos

```yaml
contentOrigin:
  repos:
    - repoid: rhel-9-5-baseos-rpms
      baseurl: "https://rhsm-pulp.corp.redhat.com/content/dist/rhel9/9.5/$basearch/baseos/os/"
    - repoid: rhel-9-5-baseos-source
      baseurl: "https://rhsm-pulp.corp.redhat.com/content/dist/rhel9/9.5/$basearch/baseos/source/SRPMS/"
    - repoid: rhel-9-5-appstream-rpms
      baseurl: "https://rhsm-pulp.corp.redhat.com/content/dist/rhel9/9.5/$basearch/appstream/os/"
    - repoid: rhel-9-5-appstream-source
      baseurl: "https://rhsm-pulp.corp.redhat.com/content/dist/rhel9/9.5/$basearch/appstream/source/SRPMS/"
```

and that's giving me

```
Traceback (most recent call last):
  File "/.../bin/rpm-lockfile-prototype", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/.../rpm-lockfile-prototype/rpm_lockfile/__init__.py", line 439, in main
    process_arch(
  File "/.../rpm-lockfile-prototype/rpm_lockfile/__init__.py", line 244, in process_arch
    packages, sources, module_metadata = resolver(
                                         ^^^^^^^^^
  File "/.../rpm-lockfile-prototype/rpm_lockfile/__init__.py", line 146, in resolver
    base.reinstall(pkg)
  File "/usr/lib/python3.12/site-packages/dnf/base.py", line 2373, in reinstall
    raise dnf.exceptions.PackagesNotAvailableError(
dnf.exceptions.PackagesNotAvailableError: no package matched: python3-libs
```

I tried several times and the not available package is one of {`python3`, `python3-libs`, `krb5-libs`}
(I verified those packages are available in the repos).
Can you see what's wrong? Thanks!

**Comment by jpopelka** [comment]
[Closing](https://redhat-internal.slack.com/archives/C066HLR2RGA/p1731313898182989)
