### ISSUE TITLE
unrecognized signature format

### ISSUE THREAD

**Issue by tkdchen** [konflux-ci/rpm-lockfile-prototype#8]
Run: `rpm-lockfile-prototype -f ./Dockerfile rpms.in.yaml`

Then, get output:

```
INFO:root:Running solver for x86_64
INFO:root:Copying rpmdb from base image
INFO:root:$ podman run --rm -ti --arch=x86_64 --pull=newer --volume=/tmp/tmp2f34rs7g/usr/lib/sysimage/rpm:/dest:z registry.access.redhat.com/ubi9/go-toolset@sha256:f001ad1001a22fe5f6fc7d876fc172b01c1b7dcd6c498f83a07b425e24275a79 sh -c 'cp -r $(rpm --eval %_dbpath)/* /dest/'
Trying to pull registry.access.redhat.com/ubi9/go-toolset@sha256:f001ad1001a22fe5f6fc7d876fc172b01c1b7dcd6c498f83a07b425e24275a79...
WARN[0005] Signature "https://access.redhat.com/webassets/docker/content/sigstore/ubi9/go-toolset@sha256=cc5b93478d74c7a67d3add8be3b41a900f6c97b0cece878465d6aa84edb0e693/signature-2" has Content-Type "text/html; charset=UTF-8", unexpected for a signature 
Error: copying system image from manifest list: Source image rejected: parsing signature https://access.redhat.com/webassets/docker/content/sigstore/ubi9/go-toolset@sha256=cc5b93478d74c7a67d3add8be3b41a900f6c97b0cece878465d6aa84edb0e693/signature-2: unrecognized signature format, starting with binary 0x3c
Traceback (most recent call last):
  File "/home/cqi/code/konflux/rpm-lockfile-prototype/venv/bin/rpm-lockfile-prototype", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/cqi/code/konflux/rpm-lockfile-prototype/rpm_lockfile/__init__.py", line 314, in main
    process_arch(
  File "/home/cqi/code/konflux/rpm-lockfile-prototype/rpm_lockfile/__init__.py", line 201, in process_arch
    with rpmdb(arch) as root_dir:
  File "/usr/lib64/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/cqi/code/konflux/rpm-lockfile-prototype/rpm_lockfile/__init__.py", line 169, in worker
    func(root_dir, arch)
  File "/home/cqi/code/konflux/rpm-lockfile-prototype/rpm_lockfile/__init__.py", line 185, in <lambda>
    lambda root_dir, arch: setup_rpmdb(root_dir, baseimage, arch, pull)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cqi/code/konflux/rpm-lockfile-prototype/rpm_lockfile/__init__.py", line 74, in setup_rpmdb
    logged_run(cmd, check=True)
  File "/home/cqi/code/konflux/rpm-lockfile-prototype/rpm_lockfile/__init__.py", line 51, in logged_run
    return subprocess.run(cmd, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['podman', 'run', '--rm', '-ti', '--arch=x86_64', '--pull=newer', '--volume=/tmp/tmp2f34rs7g/usr/lib/sysimage/rpm:/dest:z', 'registry.access.redhat.com/ubi9/go-toolset@sha256:f001ad1001a22fe5f6fc7d876fc172b01c1b7dcd6c498f83a07b425e24275a79', 'sh', '-c', 'cp -r $(rpm --eval %_dbpath)/* /dest/']' returned non-zero exit status 125.
```

**Comment by tkdchen** [comment]
Content of `rpm.in.yaml`:

```yaml
contentOrigin:
  repofiles:
    - ./fedora.repo

packages:
  # list of rpm names to resolve
  - vim-enhanced
```

**Comment by tkdchen** [comment]
Probably I used it in a wrong case.
